doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '8.0.32'
        profiling_collect_backtrace: '%kernel.debug%'
        default_table_options:
          charset: utf8mb4
          collation: utf8mb4_unicode_ci
          collate: utf8mb4_unicode_ci
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          User:
            type: 'xml'
            dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Mapping'
            prefix: 'App\User\Domain\Model'
            alias: User
          Product:
            type: 'xml'
            dir: '%kernel.project_dir%/src/Product/Infrastructure/Persistence/Mapping'
            prefix: 'App\Product\Domain\Model'
            alias: Product
        controller_resolver:
            auto_mapping: false

