# config/packages/messenger.yaml
framework:
  messenger:
    default_bus: command.bus
    buses:
      command.bus:
        default_middleware: true
        middleware:
          - App\Shared\Infrastructure\Symfony\Messenger\CustomExceptionMiddleware
          - doctrine_ping_connection
          - doctrine_close_connection
      query.bus:
        default_middleware: true
        middleware:
          - App\Shared\Infrastructure\Symfony\Messenger\CustomExceptionMiddleware
          - doctrine_ping_connection
          - doctrine_close_connection
      event.bus:
        default_middleware:
          enabled: true
          allow_no_handlers: true
        middleware:
          - App\Shared\Infrastructure\Symfony\Messenger\CustomExceptionMiddleware

    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          lazy: true
          stream: messages
          auto_setup: true

    routing:
      'App\Shared\Application\Bus\AsAsync': async
      'App\Shared\Domain\Event': async


when@test:
  framework:
    messenger:
      transports:
        async: 'in-memory://'
